config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    devise_for :admins, path: "", path_names: { sign_in: "login", sign_out: "logout"}
    root "dashboards#index"
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :authenticate_admin_admin!
end

app/controllers/admin/dashboards_controller.rb
class Admin::DashboardsController < Admin::BaseController
  def index
  end
end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < Devise::SessionsController
  layout "admin/unauthenticate_layout"
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  private
  def after_sign_out_path_for resource_or_scope
    return new_admin_admin_session_path if resource_or_scope == :admin_admin

    super
  end

  def after_sign_in_path_for resource_or_scope
    return admin_root_path if resource_or_scope.is_a?(Admin)

    super
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true
module ApplicationHelper
  FLASH_TYPE = {
    success: "alert-success", error: "alert-error", failed: "alert-failed",
    alert: "alert-danger", notice: "alert-info", danger: "alert-danger"
  }

  def flash_class flash_type
    FLASH_TYPE[flash_type] || flash_type.to_s
  end
end

app/views/admin/dashboards/index.html.erb
<h1>Admin::Dashboards#index</h1>
<p>Find me in app/views/admin/dashboards/index.html.erb</p>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Admin</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag    "https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
  <%= stylesheet_link_tag    "https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.4.1/css/simple-line-icons.min.css" %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <!-- <%= javascript_include_tag Ckeditor.cdn_url %> -->
  <%= csrf_meta_tags %>
</head>
<body id="page-top" class="page-header-fixed page-sidebar-closed-hide-logo page-sidebar-closed-hide-logo">
  <%= render "layouts/admin/header" %>
  <div id="wrapper">
    <%= render "layouts/admin/sidebar" %>
    <div id="content-wrapper">
      <%= yield %>
      <%= render "layouts/admin/footer" %>
    </div>
  </div>
</body>
</html>

app/views/layouts/admin/_footer.html.erb
<footer class="main-footer">
  <strong>Copyright &copy; 2019 - Vnbook</a>.</strong> All rights reserved.
</footer>

app/views/layouts/admin/_header.html.erb
<header class="main-header">
  <%= link_to admin_root_path, class: "logo" do %>
    <span class="logo-lg">Bookreviews</span>
  <% end %>
  <nav class="navbar navbar-static-top">
    <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
      <span class="sr-only">Toggle navigation</span>
    </a>
    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        <li class="dropdown user user-menu">
          <a href="#" class="dropdown-toggle navbar-username" data-toggle="dropdown">
            <%= image_tag "default-profile-image.png", class: "user-image" %>
            <span class="hidden-xs">
              <%= current_admin_admin.email %>
            </span>
          </a>
          <ul class="dropdown-menu">
            <li class="user-body">
              <div class="row">
                <div class="col-xs-12">
                  <%= link_to destroy_admin_admin_session_path do %>
                    <i class="fa fa-fw fa-sign-out"></i>
                    Logout
                  <% end %>
                </div>
              </div>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/admin/_navigation.html.erb
<aside class="main-sidebar">
  <section class="sidebar">
    <ul class="sidebar-menu" data-widget="tree">
      <li class="<%= 'active' if controller_name == 'top_pages' %>">
        <%= link_to admin_root_path do %>
          <span>Dashboard</span>
        <% end %>
      </li>
      <li class="treeview menu-open">
        <a href="#"><span>Bookreviews</span>
          <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu" style="display: block;">
          <li class="<%= 'active' if controller_name == 'dashboard' %>">
            <%= link_to "#" do %>
              <i class="fa fa-book"></i>
              <span><%= t(".reviews-book") %></span>
            <% end %>
          </li>
          <li class="<%= 'active' if controller_name == 'dashboard' %>">
            <%= link_to "#" do %>
              <i class="fa fa-align-justify"></i>
              <span><%= t(".category") %></span>
            <% end %>
          </li>
        </ul>
      </li>
      <li class="treeview menu-open">
        <a href="#"><span><%= t(".manage") %></span>
          <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu" style="display: block;">
          <li class="<%= 'active' if controller_name == 'dashboard' %>">
            <%= link_to "#" do %>
              <i class="fa fa-users"></i>
              <span><%= t(".manage-user") %></span>
            <% end %>
          </li>
        </ul>
      </li>
      <li class="treeview menu-open">
        <a href="#"><span><%= t(".history") %></span>
          <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu" style="display: block;">
          <li class="<%= 'active' if controller_name == 'dashboard' %>">
            <%= link_to "#" do %>
              <i class="fa fa-history"></i>
              <span><%= t(".history-admin") %></span>
            <% end %>
          </li>
          <li class="<%= 'active' if controller_name == 'dashboard' %>">
            <%= link_to "#" do %>
              <i class="fa fa-history"></i>
              <span><%= t(".history-user") %></span>
            <% end %>
          </li>
        </ul>
      </li>
    </ul>
  </section>
</aside>

app/views/layouts/admin/base.html.erb
<!DOCTYPE html>
<html lang="vi">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Admin</title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <%= stylesheet_link_tag :application_admin, media: "all" %>
    <!-- <%= javascript_include_tag Ckeditor.cdn_url %> -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
    <%= csrf_meta_tags %>
  </head>
  <body class="hold-transition skin-black sidebar-mini">
    <div class="wrapper">
      <%= render "layouts/admin/header" %>
      <%= render "layouts/admin/navigation" %>
      <div class="content-wrapper">
        <section class="content-header">
          <%= render "shared/flash" %>
          <% if content_for?(:page_title) %>
            <div class="content-main-page-header">
              <h1 class="main-page-title"><%= yield(:page_title) %></h1>
            </div><br>
          <% end %>
        </section>
        <section class="content">
          <%= yield %>
        </section>
      </div>
      <%= render "layouts/admin/footer" %>
    </div>
    <%= javascript_include_tag :application_admin %>
    <script>
      $.widget.bridge("uibutton", $.ui.button);
    </script>
  </body>
</html>

app/views/layouts/admin/unauthenticate_layout.html.erb
<!DOCTYPE html>
<html lang="vi">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Login</title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <%= stylesheet_link_tag :application_admin, media: "all" %>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
    <%= csrf_meta_tags %>
    <meta name="google" content="notranslate">
  </head>
  <body class="<%= yield :body_class %>">
    <%= yield %>
    <%= javascript_include_tag :application_admin %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vnbook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_flash.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= flash_class type.to_sym %> flash-notice">
    <a class="close" data-dismiss="alert" href="#" aria-hidden="true">&times;</a>
    <p class="text-center"><%= message.html_safe %></p>
  </div>
<% end %>